SportsStore/Models/Cart.cs
using System.Collections.Generic;
using System.Linq;


namespace SportsStore.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>(); 
        public virtual void AddItem(Product product, int quantity)
        {
            CartLine line = lineCollection
            .Where(p => p.Product.ProductID == product.ProductID)
            .FirstOrDefault();
            if (line == null)
            {
                lineCollection.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }

            else
            {
                line.Quantity += quantity;
            }
        }
        public virtual void RemoveLine(Product product) => //xóa sản phẩm đã chọn 
        lineCollection.RemoveAll(l => l.Product.ProductID == product.ProductID);
        public virtual decimal ComputeTotalValue() => //tính tổng tiền 
        lineCollection.Sum(e => e.Product.Price * e.Quantity);
        public virtual void Clear() => lineCollection.Clear(); // reset giỏ hàng 
        public virtual IEnumerable<CartLine> Lines => lineCollection; //thuộc tính cho phép truy cập vào nội dung của giỏ hàng <cart line> 
    }
    public class CartLine ////dòng giỏ hàng 
    {
        public int CartLineID { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

SportsStore/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Infrastructure;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
    public class CartController : Controller 
    {
        private IProductRepository repository; // kết nối cơ sở dữ liệu 
        private Cart cart;
        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel //Index lấy đối tượng Cart và sử dụng nó để tạo CartIndexView
            {                                  //cuối cùng để hiển thị nội dung của giỏ hàng
                Cart = cart, 
                ReturnUrl = returnUrl 
            });
        }
        
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
            
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                //Cart cart = GetCart();
                cart.AddItem(product, 1);
               // SaveCart(cart);
            }
            return RedirectToAction("Index", new { returnUrl }); // RedirectToActionResult là trả về cái đường dẫn là returnURL là return lại chính giỏ hàng 
        }
        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                    .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                //Cart cart = GetCart();
                cart.RemoveLine(product);
                //SaveCart(cart);
            }
            return RedirectToAction("Index", new { returnUrl }); // RedirectToActionResult là trả về cái đường dẫn là returnURL là return lại chính giỏ hàng 
        }
        //private Cart GetCart()
        //{
        //    Cart cart = HttpContext.Session.GetJson<Cart>("Cart") ?? new Cart();
        //    return cart;
        //}
        //private void SaveCart(Cart cart)
        //{
        //    HttpContext.Session.SetJson("Cart", cart);
        //}
    }
}

SportsStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace SportsStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;
        
        public OrderController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        [Authorize] // yeu cau dang nhap moi dung duoc 
        public ViewResult List() =>         // Phương thức List chọn tất cả các đối tượng Đặt hàng trong kho lưu trữ có giá trị Đã vận chuyển là false và
                                                //chuyển chúng sang dạng xem mặc định. và hiện danh sách cho admin 
                View(repository.Orders.Where(o => !o.Shipped));

        [HttpPost]
        [Authorize] // yeu cau dang nhap moi dung duoc 
        public IActionResult MarkShipped(int orderID)   //Phương thức MarkShipped sẽ nhận yêu cầu POST chỉ định ID của một đơn đặt hàng,sử dụng để lấy Order object 
        {                                               //để thuộc tính Đã vận chuyển được lưu và đặt là true 
            Order order = repository.Orders
            .FirstOrDefault(o => o.OrderID == orderID);
            if (order != null)
            {
                order.Shipped = true;
                repository.SaveOrder(order);
            }
            return RedirectToAction(nameof(List));
        }
        public ViewResult Checkout() => View(new Order()); //Phương thức Checkout trả về chế độ xem mặc định và
                                                           //chuyển một đối tượng ShippingDetails mới làm chế độ xem mô hình
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }
            public ViewResult Completed()
            {
                cart.Clear();
                return View();
            }
        }
    
    }

SportsStore/Views/Cart/Index.cshtml
@using SportsStore.Models
@using SportsStore.Models.ViewModels
@using SportsStore.Infrastructure             @*cập nhật partial view mô tả từng sản phẩm để Add To Cart button*@
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper SportsStore.Infrastructure.*, SportsStore

@model SportsStore.Models.ViewModels.CartIndexViewModel
<h2>Your cart</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.Name</td>
            <td class="text-right">@line.Product.Price.ToString("c")</td>
            <td class="text-right">
                @((line.Quantity * line.Product.Price).ToString("c"))
            </td>

            <td>
                <form asp-action="RemoveFromCart" asp-controller="Cart" method="post">
                    <input type="hidden" name="ProductID" value="@line.Product.ProductID" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                </form>
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">
        Checkout
    </a>
</div>