SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart; // tổng hợp giỏ hàng 
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq; //Trong phương thức Invoke tôi sử dụng LINQ để chọn và sắp xếp bộ danh mục trong kho lưu trữ và chuyển
                   //chúng làm đối số cho phương thức View 
using SportsStore.Models;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {


        //public string Invoke() //Phương thức gọi được chèn vào HTML được gửi tới trình duyệt.
        // {
        //     return "Hello from the Nav View Component"; 
        //}
        private IProductRepository repository;
        public NavigationMenuViewComponent(IProductRepository repo)     //gọi danh sách product ra  
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];// nhận mục ngay slidebar đang chọn  và chỉ route để hiển thị đúng nội dung 
            return View(repository.Products  //load danh sách sản phẩm 
            .Select(x => x.Category)           // select gần giống sql  
            .Distinct()                        // loại trừ những cái lặp lại 
            .OrderBy(x => x));                   
        }
    }
}

SportsStore/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Infrastructure;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
    public class CartController : Controller 
    {
        private IProductRepository repository; // kết nối cơ sở dữ liệu 
        private Cart cart;
        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel //Index lấy đối tượng Cart và sử dụng nó để tạo CartIndexView
            {                                  //cuối cùng để hiển thị nội dung của giỏ hàng
                Cart = cart, 
                ReturnUrl = returnUrl 
            });
        }
        
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
            
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                //Cart cart = GetCart();
                cart.AddItem(product, 1);
               // SaveCart(cart);
            }
            return RedirectToAction("Index", new { returnUrl }); // RedirectToActionResult là trả về cái đường dẫn là returnURL là return lại chính giỏ hàng 
        }
        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                    .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                //Cart cart = GetCart();
                cart.RemoveLine(product);
                //SaveCart(cart);
            }
            return RedirectToAction("Index", new { returnUrl }); // RedirectToActionResult là trả về cái đường dẫn là returnURL là return lại chính giỏ hàng 
        }
        //private Cart GetCart()
        //{
        //    Cart cart = HttpContext.Session.GetJson<Cart>("Cart") ?? new Cart();
        //    return cart;
        //}
        //private void SaveCart(Cart cart)
        //{
        //    HttpContext.Session.SetJson("Cart", cart);
        //}
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model SportsStore.Models.Product 

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>

    @*<div class="card-text p-1">@Model.Description</div> dòng mô tả *@ 

     <form id="@Model.ProductID" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" /> @*xác định đường dẫn nào được chọn*@ 
        <input type="hidden" name="returnUrl"       @*return lại đường dẫn URL*@ 
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description @* mô tả *@
            <button type="submit"
                    class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body class="m-1 p-1">

    <div class="bg-info p-2 row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </div>
    </div>
    <div class="bg-info p-2"><h4>@ViewBag.Title</h4></div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"] </div> @*hien messaga thong bao khi da luu thanh cong*@
    }

    @RenderBody()
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    <title>SportsStore</title>
</head>
<body>
    <div class="navbar navbar-inverse bg-inverse" role="navigation">
        @*<a class="navbar-brand" href="#">SPORTS STORE</a>*@
        <div class="row">
            <a class="col navbar-brand" href="#">SPORTS STORE</a>
        </div>
        <div class="col-4 text-right">
                @await Component.InvokeAsync("CartSummary")   @*Khi giỏ hàng trống, hiển thị  thanh toán
                                                              Nếu có các mặt hàng vào giỏ hàng, thì số lượng mặt hàng 
                                                               và chi phí kết hợp của chúng sẽ được hiển thị*@
        </div>
        
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <!--Put something useful here later -->
            @await Component.InvokeAsync("NavigationMenu")      <!-- gọi hàm invoke được thì load lên phần navigation menu view lên -->
        </div>
        <div class="col-9">
            @RenderBody() <!-- lay view qua su dung qua day-->
        </div>
    </div>
</body>
</html>